# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Mini_pyr_1
author: Daniella Guerra

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Darally06/MINI_PRY_1.git # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_plotly: true
